### ISSUE TITLE
Stop Trail version popup

### ISSUE THREAD

**Issue by balarvs2002** [AlexandrNikulin/AnimationNavigationPage#16]
How do I stop trial version Pop up ? I have to give a demo for my clients, If popup comes in between, They may feel some think awkward .

**Comment by AlexandrNikulin** [comment]
@balarvs2002  Hi! You see popup only in free version. Paid component hasn't this alert.
Please send me email on "nikulin.alexandr.1991@gmail.com" - maybe i can send  discount to you.

**Comment by balarvs2002** [comment]
I just need it for 3 weeks to show demo for stakeholders.  Once it is approved, Then I will indeed purchase it.  Can you please do some thing for 3 weeks ?

**Comment by AlexandrNikulin** [comment]
Hi!

Ok, i understand your problem. So let’s do this - i will send you dlls with
last version.
But after (if demo is success) you will send this 26$ to my paypal. For
Xamarin.Components i will send you promo code.
Ok?

Also i can sell source of this control for you with big discount.



And if you interested - please take a look on my UI Kit for Xamarin.Forms.
Demo : Android
<https://appetize.io/embed/r0empkb48r755x01j6h345j0f4?device=nexus5&scale=75&orientation=portrait&osVersion=7.0>
, iOS
<https://appetize.io/embed/nbmf61eq18ub054ztd71058j00?device=iphone6&scale=75&autoplay=false&orientation=portrait&deviceColor=black&osVersion=9.3>
.
Little doc:
https://www.dropbox.com/s/dds91hjigxej55r/UI%20Kit%20doc%20%28ver%200.1%29.pdf?dl=0
APK file:
https://www.dropbox.com/s/d381sigw3i7kf54/com.alexandr.demo.apk?dl=0



If you need my help - you are welcome


Thanks, Alex

От 19 февраля 2017 г. в 18:13:17, balarvs2002 (notifications@github.com)
написал:

I just need it for 3 weeks to show demo for stakeholders. Once it is
approved, Then I will indeed purchase it. Can you please do some thing for
3 weeks ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/AlexandrNikulin/AnimationNavigationPage/issues/16#issuecomment-280925225>,
or mute the thread
